моя новая функция
тут вызов функции
третья запись
делаю новую запись
что-то тут происходит
проверяем разрешение конфликта

